/*
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Matchquality struct for Matchquality
type Matchquality struct {
	Matchcode string `json:"matchcode,omitempty"`
	Matchtype string `json:"matchtype,omitempty"`
	Matchlevel string `json:"matchlevel,omitempty"`
}
