/*
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DirectionsDirectionsRoutes struct for DirectionsDirectionsRoutes
type DirectionsDirectionsRoutes struct {
	Legs []map[string]interface{} `json:"legs,omitempty"`
	WeightName string `json:"weight_name,omitempty"`
	Geometry string `json:"geometry,omitempty"`
	Weight float32 `json:"weight,omitempty"`
	Distance float32 `json:"distance,omitempty"`
	Duration float32 `json:"duration,omitempty"`
}
