/*
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DirectionsMatching struct for DirectionsMatching
type DirectionsMatching struct {
	Code string `json:"code,omitempty"`
	Tracepoints []map[string]interface{} `json:"tracepoints,omitempty"`
	Matchings []map[string]interface{} `json:"matchings,omitempty"`
}
